<li><a href="instalaciones.php">Instalaciones Previas</a></li>
<li><a href="tablas.php">Tablas</a></li>
<li><a href="validadores.php">Validadores</a></li>
<li><a href="creacion.php">Formularios</a></li>
<li><a href="modal.php">Formularios Ventanas Emergentes</a></li>
<li><a href="graficas.php">Graficas PIE/BAR/LINE</a></li>
<li><a href="editor.php">Editor de Texto Enriquecido</a></li>
<li><a href="tabs.php">TabIndex</a></li>
<li><a href="tooltip.php">Tooltip</a></li>
<li><a href="autocomplete.php">Autocomplete</a></li>
<li><a href="mhorizontal.php">Menu Horizontal</a></li>
<li><a href="mvertical.php">Menu Vertical</a></li>
<li><a href="pbar.php">Progress Bar</a></li>
<li><a href="trazabilidad.php">Trazabilidad</a></li>
<li><a href="dropdown.php">Combobox Base de Datos</a></li>
<li><a href="dropdownmultipleBD.php">Combobox Base de Datos Multiple</a></li>
<!--<li><a href="aplicacionbeta.php">Aplicacion Beta Normal</a></li>
<li><a href="aplicacionbeta2.php">Aplicacion Beta con CRUD Fachada</a></li>-->
<li><a href="fileupload.php">Subir Archivo (1 solo archivo)</a></li>
<li><a href="fileuploadmultiple.php">Subir Multiples Archivos (n archivos)</a></li>
<li><a href="multiplesinsert.php">Insertar registro en multiples tablas / multiples registros</a></li>
<li><a href="aplicacionbeta2.php">Gestor Formatos</a></li>
<li><a href="dashboard.php">Dashboard</a></li>
<li><a href="detcapitulo.php">Detalle Capitulo</a></li>
<li><a href="detformato.php">Detalle Formato</a></li>
<li><a href="listcapitulos.php">Listado Capitulo</a></li>
<li><a href="formatoHTML.php">Formato HTML</a></li>
<li><a href="documentosPDF.php">Generar PDF</a></li>
